
version: '3.7'
services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        image: oda-api-image
        container_name: oda-api-supplier
        restart: unless-stopped
        environment:
            PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
            PHP_XDEBUG_REMOTE: ${PHP_XDEBUG_REMOTE}
        volumes:
            - ./:/var/www/html
        networks:
            - oda-api

    mysql_db:
        image: mysql:5.7
        container_name: oda-api-db
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        expose:
          - 3309
        ports:
          - 3309:3309
        volumes:
          - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "false"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_TCP_PORT: 3309
        networks:
          - oda-api

    nginx:
      image: nginx:latest
      container_name: oda-api-nginx
      restart: unless-stopped
      volumes:
          - ./docker/config/nginx:/etc/nginx/conf.d/
          - ./docker/logs/nginx:/var/log/nginx/
          - ./:/var/www/html
      networks:
          - oda-api
      ports:
          - "3000:80"
      healthcheck:
          test: wget --quiet --tries=1 --spider http://localhost || exit 1z
          interval: 30s
          timeout: 10s
          retries: 5
      depends_on:
        - app

    redis:
      image: redis:6.2-alpine
      container_name: oda-api-redis
      restart: unless-stopped
      command: --port 6379
      ports:
          - "6379:6379"
      expose:
          - "6379"
      networks:
          - oda-api
      healthcheck:
          test: ["CMD", "redis-cli","ping"]
          interval: 30s
          timeout: 10s
          retries: 5
networks:
    oda-api:
        driver: bridge

volumes:
  mysql_data:
    name: mysql_data